@startuml GameSequence

actor User as user #BlanchedAlmond
participant ":UI" as ui #IndianRed
participant ":Parser" as parser #LightPink
participant ":Game" as game #Orchid
participant ":ChessBoard" as board #Orange
participant ":CPU" as cpu #SkyBlue
participant ":Storage" as storage #PaleTurquoise

activate game #AliceBlue

loop hasGameEnded

    game -> ui : getUserInput()
    activate ui
    user -> ui : input
    ui --> game : userInputString :String
    deactivate ui

    game -> parser : parseCommand(userInputString)
    activate parser
    parser --> game : :Command
    deactivate parser

    opt isMoveCommand

        game -> parser : parseMove(input)
        activate parser
        parser --> game : humanMove:Move
        deactivate parser

        game -> board : executeMove(humanMove)
        activate board
        board --> game
        deactivate board

        game -> storage : saveBoard()
        activate storage
        storage --> game
        deactivate storage

        game -> cpu : getBestMove()
        activate cpu
        cpu --> game : cpuMove:Move
        deactivate cpu

        game -> board : executeMove(cpuMove)
        activate board
        board --> game
        deactivate board

        game -> storage : saveBoard()
        activate storage
        storage --> game
        deactivate storage

        game -> board : checkEndState()
        activate board
        board --> game : hasGameEnded:bool
        deactivate board

    end

end

game --> user
destroy game

@enduml
