@startuml
hide circle
skinparam classAttributeIconSize 0

class Move {
  - from: Coordinate
  - to: Coordinate
  - pieceMoved: ChessPiece
  - pieceCaptured: ChessPiece

  + getFrom(): Coordinate
  + getTo(): Coordinate
  + getPieceMoved(): ChessPiece
  + hasCapturedAPiece(): boolean
  + getPieceCaptured(): ChessPiece
  + isValidWithCheck(board: ChessBoard): boolean
  + isSkippingPawn(): boolean
  + toString(): String
}
@enduml
