@startuml
class Storage {
  - filePathString: String
  - storageFile: File

  + Storage(filePath: String)
  + saveBoard(board: ChessBoard, playerColor: Color): void
  + resetBoard(): void
  + loadBoard(): ChessTile[][]
  + loadPlayerColor(): Color

  - createChessMasterFile(): void
}

class ChessBoard {
  - SIZE: int
}

class ChessTile

class Color

Storage -[hidden]-> File
Storage --|> ChessBoard
Storage --|> ChessTile
Storage --|> Color
@enduml
